#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookdb
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
